//go:build ignore

// gen_entities writes entities.go, the table of HTML named character
// references, from the names in testdata/entities/entities.json that end with
// a semicolon.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"log"
	"os"
	"slices"
	"strings"
)

func main() {
	data, err := os.ReadFile("testdata/entities/entities.json")
	if err != nil {
		log.Fatal(err)
	}
	var refs map[string]struct{ Characters string }
	if err := json.Unmarshal(data, &refs); err != nil {
		log.Fatal(err)
	}
	var names []string
	for ref := range refs {
		if name, ok := strings.CutSuffix(strings.TrimPrefix(ref, "&"), ";"); ok {
			names = append(names, name)
		}
	}
	slices.Sort(names)
	var b bytes.Buffer
	b.WriteString(`// Code generated by gen_entities.go from testdata/entities/entities.json; DO NOT EDIT.

package markdown

// entities maps each HTML entity name that ends with a semicolon, without
// its "&" and ";", to its characters, in name order.
var entities = [...]entity{
`)
	for _, name := range names {
		fmt.Fprintf(&b, "\t{%q, %+q},\n", name, refs["&"+name+";"].Characters)
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("entities.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
}
