//go:build ignore

// gen_width writes width.go, the ranges of wide characters, from the W and F
// rows of testdata/unicode/EastAsianWidth.txt.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strconv"
	"strings"
)

func main() {
	data, err := os.ReadFile("testdata/unicode/EastAsianWidth.txt")
	if err != nil {
		log.Fatal(err)
	}
	var b bytes.Buffer
	b.WriteString(`// Code generated by gen_width.go from testdata/unicode/EastAsianWidth.txt; DO NOT EDIT.

package markdown

// wideRanges holds the ranges of characters whose East Asian Width is W or F,
// in code point order, with adjacent ranges merged.
var wideRanges = [...]runeRange{
`)
	var lo, hi uint64
	open := false
	for line := range strings.Lines(string(data)) {
		row, _, _ := strings.Cut(line, "#")
		codes, width, ok := strings.Cut(row, ";")
		if width = strings.TrimSpace(width); !ok || width != "W" && width != "F" {
			continue
		}
		first, last, ranged := strings.Cut(strings.TrimSpace(codes), "..")
		if !ranged {
			last = first
		}
		l, err := strconv.ParseUint(first, 16, 32)
		if err != nil {
			log.Fatal(err)
		}
		h, err := strconv.ParseUint(last, 16, 32)
		if err != nil {
			log.Fatal(err)
		}
		if open && l == hi+1 {
			hi = h
			continue
		}
		if open {
			fmt.Fprintf(&b, "\t{0x%04X, 0x%04X},\n", lo, hi)
		}
		lo, hi, open = l, h, true
	}
	if open {
		fmt.Fprintf(&b, "\t{0x%04X, 0x%04X},\n", lo, hi)
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("width.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
}
