//go:build ignore

// gen_casefold writes casefold.go, the Unicode full case folding table, from
// the C and F rows of testdata/unicode/CaseFolding.txt.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strconv"
	"strings"
)

func main() {
	data, err := os.ReadFile("testdata/unicode/CaseFolding.txt")
	if err != nil {
		log.Fatal(err)
	}
	var b bytes.Buffer
	b.WriteString(`// Code generated by gen_casefold.go from testdata/unicode/CaseFolding.txt; DO NOT EDIT.

package markdown

// caseFolds maps each character that Unicode full case folding changes to
// its folding: the C and F rows of CaseFolding.txt, in code point order.
var caseFolds = [...]caseFold{
`)
	for line := range strings.Lines(string(data)) {
		fields := strings.Split(line, "; ")
		if strings.HasPrefix(line, "#") || len(fields) < 3 || fields[1] != "C" && fields[1] != "F" {
			continue
		}
		r, err := strconv.ParseUint(fields[0], 16, 32)
		if err != nil {
			log.Fatal(err)
		}
		var to []rune
		for code := range strings.FieldsSeq(fields[2]) {
			c, err := strconv.ParseUint(code, 16, 32)
			if err != nil {
				log.Fatal(err)
			}
			to = append(to, rune(c))
		}
		fmt.Fprintf(&b, "\t{0x%04X, %+q},\n", r, string(to))
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("casefold.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
}
